export default {
  name: 'homepage',
  title: 'Homepage',
  type: 'document',
  fields: [
    { name: 'title', title: 'Internal Title', type: 'string', initialValue: 'Homepage' },
    { name: 'heroHeading', title: 'Hero Heading', type: 'string', validation: (Rule: any) => Rule.required().max(80) },
    { name: 'heroSubtitle', title: 'Hero Subtitle', type: 'text', rows: 3, validation: (Rule: any) => Rule.required().max(220) },
    { name: 'heroImage', title: 'Hero Image', type: 'image', options: { hotspot: true } },
    { name: 'primaryCtaText', title: 'Primary CTA Text', type: 'string' },
    { name: 'primaryCtaLink', title: 'Primary CTA Link', type: 'string' },
    { name: 'secondaryCtaText', title: 'Secondary CTA Text', type: 'string' },
    { name: 'secondaryCtaLink', title: 'Secondary CTA Link', type: 'string' },
    { name: 'collectionTitle', title: 'Collection Section Title', type: 'string' },
    { name: 'collectionCopy', title: 'Collection Section Copy', type: 'text', rows: 4 },
    { name: 'giftTitle', title: 'Gift Section Title', type: 'string' },
    { name: 'giftCopy', title: 'Gift Section Copy', type: 'text', rows: 4 },
    { name: 'newsletterTitle', title: 'Newsletter Title', type: 'string' },
    { name: 'newsletterCopy', title: 'Newsletter Copy', type: 'text', rows: 3 },
    {
      name: 'featuredProductSlugs',
      title: 'Featured Product Slugs',
      type: 'array',
      of: [{ type: 'string' }],
      description: 'Use product slugs from Supabase, for example crimson-crystal.',
    },
    {
      name: 'featuredCategorySlugs',
      title: 'Featured Category Slugs',
      type: 'array',
      of: [{ type: 'string' }],
    },
  ],
}
